config/routes.rb
Rails.application.routes.draw do

    root 'pitching_stats#scraped_pitching_wars'

    resources :pitching_stats


    get 'scraped_batting_wars', to: 'batting_stats#scraped_batting_wars'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batting_stat.rb
class BattingStat < ApplicationRecord
    validates_presence_of :war, :team_batting
    

end

app/models/pitching_stat.rb
class PitchingStat < ApplicationRecord
  validates_presence_of :pitching_war, :team_pitching

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/batting_stats_controller.rb
class BattingStatsController < ApplicationController

  def scraped_batting_wars
    @battingstats = BattingStat.all
  end
end

app/controllers/pitching_stats_controller.rb
class PitchingStatsController < ApplicationController

  def scraped_pitching_wars
    @pitchingstats = PitchingStat.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batting_stats_helper.rb
module BattingStatsHelper
end

app/helpers/pitching_stats_helper.rb
module PitchingStatsHelper
end

app/views/batting_stats/scrape_espn.html.erb
<h1>Current Marlins OPS</h1>

<ul>
  <% @battingstats.each do |battingstat|  %>
  <li> <%= battingstat.ops %></li>
  <li> <%= battingstat.team_batting %></li>
</ul>
<% end %>

app/views/batting_stats/scraped_batting_wars.html.erb
<h1>Current Batting WARs</h1>

<ul>
  <% @battingstats.each do |battingstat|  %>
  <li> <%= battingstat.war %></li>
  <li> <%= battingstat.team_batting %></li>
</ul>
<% end %>

<%= link_to "Pitching WARs", :root %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WARs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pitching_stats/scraped_pitching_wars.html.erb
<h1>Current Pitching WARs</h1>

<ul>
  <% @pitchingstats.each do |pitchingstat|  %>
  <li><%= pitchingstat.pitching_war %></li>
  <li><%= pitchingstat.team_pitching %></li>
</ul>
<% end %>

<%= link_to "Batting WARs", scraped_batting_wars_path %>